# Generated by Django 5.2.6 on 2025-09-25 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('field_setup', 'Field Setup'), ('training_equipment', 'Training Equipment'), ('match_equipment', 'Match Equipment'), ('safety_recovery', 'Safety & Recovery'), ('event_accessories', 'Event Accessories'), ('player_gear', 'Player Gear')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
