# Generated by Django 5.2.6 on 2025-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('field_setup', 'Field Setup'), ('training_equipment', 'Training Equipment'), ('match_equipment', 'Match Equipment'), ('safety_recovery', 'Safety & Recovery'), ('event_accessories', 'Event Accessories'), ('player_gear', 'Player Gear')], max_length=20),
        ),
    ]
